FROM python:3.9 As builder
WORKDIR /app
COPY payment.ini .
COPY *.py .
COPY requirements.txt .
RUN pip3 install -r requirements.txt

FROM python:3.9-slim
WORKDIR /app
RUN pip install --no-cache-dir -r requirements.txt
COPY --from=builder /app /app
ENV CART_HOST=cart \
    CART_PORT=8080 \
    USER_HOST=user \
    USER_PORT=8080 \
    AMQP_HOST=rabbitmq \
    AMQP_USER=roboshop \
    AMQP_PASS=roboshop123
CMD ["uwsgi","--ini","payment.ini"]
