FROM python:3.9
WORKDIR /app
COPY payment.ini .
COPY *.py .
COPY requirements.txt .
RUN pip3 install -r requirements.txt
RUN groupadd roboshop && useradd -g roboshop roboshop && \
    chown -R roboshop:roboshop /app
# ENV CART_HOST=cart \
#     CART_PORT=8080 \
#     USER_HOST=user \
#     USER_PORT=8080 \
#     AMQP_HOST=rabbitmq \
#     AMQP_USER=roboshop \
#     AMQP_PASS=roboshop123
USER roboshop
CMD ["uwsgi","--ini","payment.ini"]
