networks:
   roboshop:
    external: true

services:
  catalogue:
   build: ./catalogue
   image : saithota9/catalogue:1.0.0
   container_name: catalogue
   depends_on:
      - mongodb
  frontend:
   build: ./frontend
   image : saithota9/frontend:1.0.0
   container_name: frontend
   ports:
    - "80:80"
   depends_on:
   - catalogue
   - user
   - cart
   - shipping
   - payment
  user:
   build: ./user
   image : saithota9/user:1.0.0
   container_name: user
   depends_on:
      - mongodb
      - redis
  cart:
   build: ./cart  
   image : saithota9/cart:1.0.0
   container_name: cart
   depends_on:
      - redis
  shipping:
   build: ./shipping  
   image : saithota9/shipping:1.0.0
   container_name: shipping
   depends_on:
      - mysql
  payment:
   build: ./payment  
   image : saithota9/payment:1.0.0
   container_name: payment
   depends_on:
      - mysql
  mongodb:
   build: ./mongodb  
   image : saithota9/mongodb:1.0.0
   container_name: mongodb
   volumes: 
    - mongodb:/data/db
  mysql:
   build: ./mysql
   image : saithota9/mysql:1.0.0
   container_name: mysqldb
   volumes: 
    - mysql:/var/lib/mysql
  rabbitmq:
   build: ./rabbitmq  
   image : saithota9/rabbitmq:1.0.0
   container_name: rabbitmq
     - rabbitmq:/var/lib/rabbitmq
  redis:
   build: ./redis
   image: saithota9/redis:1.0.0
   container_name: redis
   volumes:
    - redis:/data
volumes:
  - mongodb
  - redis
  - rabbitmq
  - mysql

