FROM node:20 As builder
WORKDIR /app
COPY package.json .
COPY server.js .
RUN npm install


FROM node:20-alpine
WORKDIR /app
RUN addgroup -S roboshop && adduser -S roboshop -G roboshop && \
    chown -R roboshop:roboshop /app
COPY --from=builder /app /app
USER roboshop
# ENV REDIS_HOST=redis
# ENV CATALOGUE_HOST=catalogue
# ENV CATALOGUE_PORT=8080
CMD ["node","server.js"]