FROM maven:3.9-eclipse-temurin-17 As builder
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package
RUN mv target/*.jar shipping.jar

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=builder /app /app
ENV CART_ENDPOINT=cart:8080
ENV DB_HOST=mysql
CMD ["java","-jar","shipping.jar"]
